### ISSUE TITLE
Environment missing ipykernel

### ISSUE THREAD

**Issue by CarlWalsh-Geo** [LL-Geo/CAGE2024#1]
Hey @LL-Geo and @MareenIsabellLoesing,
I'm starting to run through some of the grav content and noticed that ipykernel isn't listed in the requirements.yml file. I'm running the notebooks in VS Code which seems to need ipykernel to run cells.  Not sure if this is an issue in other IDEs or in the online JupyterLabs, I just thought I'd mention it in case it holds things up on site :)

Thanks for the Notebooks, they're really clear and easy to follow! Looking forward to this component of the course :D

**Comment by LL-Geo** [comment]
Nice catch! I have updated the environment to add ipykernel. 
See you next week :)
